/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const ProjectCategory = IDL.Variant({
  'commercial' : IDL.Null,
  'residential' : IDL.Null,
  'industrial' : IDL.Null,
});
export const Project = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : ProjectCategory,
});
export const Testimonial = IDL.Record({
  'quote' : IDL.Text,
  'author' : IDL.Text,
  'roleOrCompany' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getProjectsByCategory' : IDL.Func(
      [ProjectCategory],
      [IDL.Vec(Project)],
      ['query'],
    ),
  'initializeData' : IDL.Func([], [], []),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const ProjectCategory = IDL.Variant({
    'commercial' : IDL.Null,
    'residential' : IDL.Null,
    'industrial' : IDL.Null,
  });
  const Project = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : ProjectCategory,
  });
  const Testimonial = IDL.Record({
    'quote' : IDL.Text,
    'author' : IDL.Text,
    'roleOrCompany' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getProjectsByCategory' : IDL.Func(
        [ProjectCategory],
        [IDL.Vec(Project)],
        ['query'],
      ),
    'initializeData' : IDL.Func([], [], []),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };